networks:
  main_network:
services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8999:80"
    networks:
      - main_network
  node:
    container_name: app
    image: example-name
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - ${PORT:-4000}:3000
    working_dir: /mnt/app
    command: >
      sh -c "pm2-runtime start /mnt/app/linux.config.js --env production"
