networks:
  main_network:
services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8999:80"
    networks:
      - main_network
  node:
    container_name: app
    image: keymetrics/pm2:14-alpine
    ports:
      - ${PORT:-4000}:3000
    working_dir: /mnt/app
    networks:
      - main_network
    volumes:
      - ./app:/mnt/app
      - /mnt/app/node_modules